### ISSUE TITLE
Rust client test regression

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1071]
https://github.com/project-serum/anchor/pull/1057 introduced a regression in the rust client tests. Probably something up with the log parsing for events.

**Comment by paul-schaaf** [comment]
@armaniferrante yes the instruction logs are not events but because it is logged from the program the client assumes it is an event

**Comment by paul-schaaf** [comment]
there's a couple ways of fixing this. it depends on who the instruction name logs are for

we can change backend

a) we can turn the instruction name logs into events and emit! them. bad for humans (event logs are encoded). requires no change in the client

or we can change the client

b) we can continue to msg! them and ignore them on the client
c) we can adjust the client so its on function can handle other things, not just events

I lean towards b).machines can parse the instruction by looking at the instruction data itself, so humans seem to benefit most from the instruction name logs.

**Comment by armaniferrante** [comment]
We should do b). An event discriminator is prefixed to the logs, which can be used to see if a log is an event or something else. The ts client should be doing this already.

**Comment by paul-schaaf** [comment]
the rust client that is used in the test also filters discriminators not belonging to events. The problem is that the client assumes that whatever it is receiving is base64 encoded, even before it decides whether it's an event or not. so the discriminator is useless because we only get to it by base64 encoding. but the instruction name log isnt base64 encoded.

potential solution is instead of erroring out when not being able to parse the incoming bytes as base64 encoded, we just return and dont throw an error. could add a debug flag that when enabled prints the incoming string if it doesn't recognise it

**Comment by armaniferrante** [comment]
Sounds good. We can just do what the ts client does.
