### ISSUE TITLE
how to call the program from a javascript (not ts) file ?

### ISSUE THREAD

**Issue by easydeveloppement** [project-serum/anchor#1372]
Hi,
i'm running my program successfully with anchor test.
I would like now to make a transaction calling my program from my javascript app (not typescript).
So i can't use IDL, etc.
I try to manually write the transaction, but i should be missing something because i have the error meaning no discriminator have been found. How can i set it in javascript ?

Why all examples are using typescript only ? is it unsafe to use js file to call anchor program ?

**Comment by zkhalapyan** [comment]
Would be great if you provided some code snippets here so that developers can further understand what you're trying to accomplish. Additionally, using TypeScript is preferential and I would advise you to start adopting it earlier the better. I would give you some of my examples, but all are using TS.

**Comment by easydeveloppement** [comment]
i was just trying to call my program in a vue app, and i managed to do it. I have put the idl in a js var, and used sol-wallet-adapter instead of nodewallet since it's not working in the browser.
