### ISSUE TITLE
unable to get program data during anchor test

### ISSUE THREAD

**Issue by eduardotang** [project-serum/anchor#1400]
all the tests passed in the test validator
but failed if using anchor test locally spawned validator

solana log will give
Custom program error: 0xbc4

and the test  failed with below error
Error: 3012: The program expected this account to be already initialized

sorry i am new to solana......
is this a solana problem? or  how the account should be initialized when deploy in the genesis block

**Comment by kklas** [comment]
How are you testing your program? Are you doing integration tests in rust using `ProgramTest` or tests writtein in typescript?

**Comment by eduardotang** [comment]
Tests written in Typescript

Yes , the tests pass if I do anchor deploy after the test validator is running 

1 solana-test-validator --reset
2 Either 
anchor deploy then anchor test
Or
anchor test --skip-local-validator
Tests pass in either case

**Comment by kklas** [comment]
It's not related to https://github.com/solana-labs/solana/pull/22694 since that issue applies only for ProgramTest integration tests written in rust, but I guess it's kind of similar.

I haven't looked at the code but I would bet that adding the program through `--bpf-program` adds it as a BpfLoader2 program which is uses different layout than the upgradeable loader and is causing your issue (similar to [22694](https://github.com/solana-labs/solana/pull/22694 )).

This has nothing to do with anchor though so I would suggest you open an issue in the solana repo.

**Comment by paul-schaaf** [comment]
not an anchor issue, so im closing this
