### ISSUE TITLE
Implement Key for Pubkey 

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1416]
https://github.com/project-serum/anchor/pull/1127/files#diff-c30312f654589dc8120c3ca5d75db6816b7825627c10c7c4b485215991bd54e7L237 removed the implementation.

**Comment by armaniferrante** [comment]
When adding the trait implementation, we get the following error

```
error[E0119]: conflicting implementations of trait `Key` for type `solana_program::pubkey::Pubkey`
   --> lang/src/lib.rs:232:1
    |
226 |   impl Key for Pubkey {
    |   ------------------- first implementation here
...
232 | / impl<'info, T> Key for T
233 | | where
234 | |     T: AsRef<AccountInfo<'info>>,
235 | | {
...   |
238 | |     }
239 | | }
    | |_^ conflicting implementation for `solana_program::pubkey::Pubkey`
  ```

**Comment by fanatid** [comment]
Am I understanding correctly that this is about https://rust-lang.github.io/rfcs/1210-impl-specialization.html ?

**Comment by schwarzbi3r** [comment]
Any reason we couldn't remove the generic impl, restricted to AccountInfo, and move them both into a regular implementation?

```rust
impl<'info> Key for AccountInfo<'info> {
    fn key(&self) -> Pubkey {
        *self.key
    }
}

impl Key for Pubkey {
    fn key(&self) -> Pubkey {
        *self
    }
}
```

I'm somewhat new to rust, so please excuse my ignorance if I'm missing something.

**Comment by schwarzbi3r** [comment]
I deleted my earlier errant comment about this. Looking at it more thoroughly, I'm not sure how to best sort this out.

The [generic implementation added](https://github.com/project-serum/anchor/pull/1127/files#diff-c30312f654589dc8120c3ca5d75db6816b7825627c10c7c4b485215991bd54e7L237) removes ~12 separate implementations of the Key trait and condenses it down to one generic implementation over `AsRef<AccountInfo>`. The downside is that Rust will not allow Pubkey to implement `Key` now as it's possible (in practice, extremely unlikely) for another upstream crate to implement `AsRef<AccountInfo>` on Pubkey and thereby create a conflict.

With regards to the specialization feature, there still seems to be some debate around it (https://github.com/rust-lang/rust/issues/31844)

There might be some other potential fixes, like using a private trait as the bounds (removing the option for upstream crates to implement it), but that seems less than ideal.

Open to suggestions, and I may be missing something really obvious.

**Comment by skrrb** [comment]
One possible workaround would be to define a custom type, and implement the trait on it

```
pub struct PubkeyWrapper(Pubkey);

impl Key for PubkeyWrapper {
    fn key(&self) -> Pubkey {
        self.0
    }
}

impl From<Pubkey> for PubkeyWrapper {
    fn from(p: Pubkey) -> Self {
        PubkeyWrapper(p)
    }
}

```
so it can be accessed as PubkeyWrapper::from(pubkey) when necessary.

**Comment by fanatid** [comment]
@skrrb this will not work too :disappointed: 
```
note: the following trait bounds were not satisfied because of the requirements of the implementation of `anchor_lang::Key` for `_`:
      `anchor_lang::prelude::Pubkey: std::convert::AsRef<anchor_lang::prelude::AccountInfo<'_>>`
   --> programs/my-stupid-program/src/lib.rs:130:6
    |
130 | impl Key for PubkeyWrapper {
```

**Comment by skrrb** [comment]
@fanatid Could you elaborate a little more what are you trying to do? rust orphan rule forbids implementing an external trait on an external type, so for a custom type there should be not problem (last paragraph of https://doc.rust-lang.org/book/ch10-02-traits.html#implementing-a-trait-on-a-type). Indeed, the following MWE doesn't produce any error

```
use anchor_lang::prelude::*;
use std::str::FromStr;

declare_id!("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");

pub struct PubkeyWrapper(Pubkey);

impl Key for PubkeyWrapper {
    fn key(&self) -> Pubkey {
        self.0
    }
}

impl From<Pubkey> for PubkeyWrapper {
    fn from(p: Pubkey) -> Self {
        PubkeyWrapper(p)
    }
}

#[program]
pub mod test {
    use super::*;
    pub fn initialize(_ctx: Context<Initialize>) -> ProgramResult {
        let pubkey = Pubkey::from_str("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA").unwrap();

        // Does not compile due to unsatisfied trait bounds
        //let foo = pubkey.key();

        // Compiles!
        let bar = PubkeyWrapper::from(pubkey).key();
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

**Comment by fanatid** [comment]
@skrrb sorry, I needed to mention that error happens in macros:

```rust
    #[account(mut, associated_token::mint = MINT_PUBKEY, associated_token::authority = account.signer)]
```

```rust
error[E0599]: the method `key` exists for struct `anchor_lang::prelude::Pubkey`, but its trait bounds were not satisfied
   --> programs/my-stupid-program/src/lib.rs:132:10
    |
132 | #[derive(Accounts)]
    |          ^^^^^^^^ method cannot be called on `anchor_lang::prelude::Pubkey` due to unsatisfied trait bounds
    |
   ::: /home/kirill/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-program-1.8.5/src/pubkey.rs:70:1
    |
70  | pub struct Pubkey([u8; 32]);
    | ----------------------------
    | |
    | doesn't satisfy `_: std::convert::AsRef<anchor_lang::prelude::AccountInfo<'_>>`
    | doesn't satisfy `anchor_lang::prelude::Pubkey: anchor_lang::Key`
    |
    = note: the following trait bounds were not satisfied:
            `anchor_lang::prelude::Pubkey: std::convert::AsRef<anchor_lang::prelude::AccountInfo<'_>>`
            which is required by `anchor_lang::prelude::Pubkey: anchor_lang::Key`
    = note: this error originates in the derive macro `Accounts` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by paul-schaaf** [comment]
A custom type should work but I dont feel great about making the user use a new type just so we can call `key` inside the constraints codegen. We could make this transparent by converting all target inputs to the new type on which we then call `.key()` but we couldnt make this conversion a blanket impl for the same reason so at that point we should just revert to the pre-blanket impl.

I feel like the better solution than a custom type, given a target `X` would be to check inside the constraints codegen whether `X` is an ident on the struct. If it is, add a `.key()` inside the constraints codegen. Otherwise, just leave it as it is. The one thing that this approach will break is composite targets. These don't exist on the struct but are accounts, not pubkeys. So users would have to add `.key()` for composite targets themselves. But maybe this is acceptable.

I lean towards reverting to the pre-blanket impl. Sure it's not as elegant but it does provide the best user experience and it's not as complex as introducing workarounds in the constraints file.

**Comment by armaniferrante** [comment]
Is this affecting anyone? The one case that was reported worked around this. And if there isn't any demand, I'd rather keep the blanket impl. Otherwise, reverting sounds good.

**Comment by paul-schaaf** [comment]
to give some more context on what doesnt work right now:

Ive seen one case reported where someone wanted to use a pubkey for their `associated_token::mint,authority` and this is now no longer possible (only way to do it is manually in the handler function or a big `constraint`). 
It would also be true for the `owner` constraint. I saw "would" because the owner constraint doesnt use the `Key` trait so users currently have to add `.key()` to the target themselves in the case of an account target (this non-usage of the `Key` trait is also true for the `address` constraint but I dont see a reason why youd ever want the address to be an account) .
It would also be true for the new token `token::mint,authority`constraints. this means that if you have a settings struct in which you save token accounts or just a different token account, you cannot do `token::mint = settings.mint_a` or `token::mint = other_token.mint` respectively.
 
Instead of reverting to pre-blanket, another solution would be to require the user to use `.key()` themselves (like it is currently done with the `owner` constraint) whereever a pubkey or an account may currently be provided. This makes the user ensure that the input is a pubkey (e.g. `payer = payer` but `associated_token::mint = mint.key()` although the `associated_token::mint` really only takes a pubkey if it's not with an init which makes the API more confusing).

**Comment by binyebarwe** [comment]
Hi, what's the status of this?

**Comment by paul-schaaf** [comment]
@binyebarwe can u describe your use case? We're not sure it makes sense to add this feature given that it would make our code uglier

**Comment by binyebarwe** [comment]
@paul-schaaf We tend to save some Pubkeys in our VaultAccount. Then we want to verify in this way. But if uncomment it fails
<img width="522" alt="Screenshot 2022-03-11 at 15 42 29" src="https://user-images.githubusercontent.com/76444437/157889218-8c6fa2fe-1694-48c9-849c-41116136e16a.png">
