### ISSUE TITLE
examples for derived accounts (named, other program, indexed)?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [project-serum/anchor#227]
# named

account A have 2 derived account key C and D, they are both derived from A key, plus some string representing entity type, like "C" and "D". A, B, C all owned by my program

it would be ok if could do compised with same state, but generic parameter as name https://github.com/project-serum/anchor/blob/master/examples/composite/programs/composite/src/lib.rs (i do not want to copy state)

will that work https://github.com/project-serum/anchor/blob/360a16657db4c74163ef0e99e3db8259e007748c/examples/cashiers-check/programs/cashiers-check/src/lib.rs#L126 ? 

# other program

same as above, but C and D are owned by different programs.  is solution compatible with CpiAccounts ? 

# indexed

account data A stores index. it is is incremented each time new derived account is created. so index value from state is used to derive program account

it is not same as https://github.com/project-serum/anchor/blob/360a16657db4c74163ef0e99e3db8259e007748c/examples/lockup/programs/registry/src/lib.rs#L1127  . I want index of one u64 number, not storing vector on chain. Cause ther are queues, bit vectors, heaps, etc. So the more stuctures possible the better. But docs about queue would be awesome either.

# are these supported?

i have seen derived and other programs are supported, but not sure about combinations. also have not seend named or indexes(based on states) derives.

**Comment by dzmitry-lahoda** [comment]
i have read all docs, and these seems supported. but i am blocked by https://github.com/project-serum/anchor/issues/228 fornow.

**Comment by armaniferrante** [comment]
If I understand correctly, it appears these questions have been answered by the documentation? Closing.

**Comment by dzmitry-lahoda** [comment]
I have found a set of other questions not in docs.
I see that all vecs in states are fixed size (fixed max size)? Could they grow? 
Also, I do not see an account state layout upgradeability. Like, same account, different layout. V1 and V2.
Also I did not see optional accounts (like is it possible to  have Option<AccountInfo> or some guide to imitate it not to copy paste whole instruction body).
And is it possible to pass array of accounts or 2 arrays of accounts of same size?
All are these scenarios from contracts I have wrote.

**Comment by armaniferrante** [comment]
* Account sizes are fixed on solana. To have variable sized vecs, you need to allocate space in the account so that they can grow. You can do this when you create an account from the client by passing in an explicit size, for example here https://github.com/project-serum/anchor/blob/master/examples/lockup/tests/lockup.js#L322. You can do this for state like this https://github.com/project-serum/anchor/blob/512604b85e9696c30519c6182a7d97e1dea29c15/examples/misc/programs/misc/src/lib.rs#L14. Or you can do it for associated accounts like this https://github.com/project-serum/anchor/blob/14edcb038ddabdaf54654d6845f8bfa6262d5a15/examples/chat/programs/chat/src/lib.rs#L39.
* There's no good way to do account versioning at the moment. If you want an upgradeable account, you need to allocate enough space, and do upgrades yourself. The easiest thing todo would be to append fields to the end of the struct, preserving the old fields on each upgrade (though this is of course far from ideal).
* To have an Option inside `#[derive(Accounts)]` you can use the `remaining_accounts` feature, which stores all accounts *not* in the accounts derive. Rust example https://github.com/project-serum/anchor/blob/8289e475136c8f2bcaeed6b1786912f350553091/examples/multisig/programs/multisig/src/lib.rs#L155. Javascript example https://github.com/project-serum/anchor/blob/c3865ac40137ddd7f30cba6692a5d2e56c3a5a83/examples/multisig/tests/multisig.js#L109. Related, you can use `Options<T>` inside an `#[account]` as you would normally.
* If you want an array, you should use `ctx.remaining_accounts`. The framework encourages one to use `#[derive(Accounts)]` structs with named fields instead of an array or slice.
