### ISSUE TITLE
Provider for devnet sends pre-flight checks even if disabled in configuration

### ISSUE THREAD

**Issue by xcjaa** [project-serum/anchor#360]
Observed this while testing on dev-net. Saw that we were getting rate limited and saw lots of pre-flight checks being sent in the browser network activity. (Chrome). 

This issue doesn't happen while on localnet. 

We pass in explicit config in the program initialisation.

Many thanks in advance!

**Comment by johnrees** [comment]
I believe this is an issue with RPC servers rather than an anchor-specific problem.

I made [this service worker](https://github.com/johnrees/rate-limited-fetch-service-worker) to throttle RPC requests recently, it solved this exact problem for us. The nice thing about using a SW is that you shouldn't need to change any of your existing code. It's in use on psyoptions if you have access to their alpha and wanted to see it in action.

The solana/web3.js library actually has inbuilt [retry functionality for failed RPC requests](https://github.com/solana-labs/solana-web3.js/blob/53be88c38dd263df25eac37533b45f300c84e44c/src/connection.ts#L738-L764) but it's only checking for `HTTTP 429` errors and some of the RPC servers don't return this code but block you via CORS when you're being throttled instead.

**Comment by armaniferrante** [comment]
Thanks for the info @johnrees. Closing. Please re-open if you think this is an issue with the anchor package.
