### ISSUE TITLE
Automatically log errors when program fails

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#798]
Programs should convert the error code into the `#[msg("<msg>")]` string and log it via `msg!`.

**Comment by paul-schaaf** [comment]
potential spec (not sure if it could actually work like this) which builds on some of the ideas of @cqfd 's PR but includes file and line information and more dynamic errors that show what exactly went wrong.

- create an AnchorError and an AnchorResult<(), AnchorError>
    - AnchorError is a struct with a `msg:String` field, an `error_code:u64` field, a line number field, and a file field
    - implements From<ProgramError> and ProgramError implements From<AnchorError>
    - autogenerated derive(Accounts) code will throw AnchorErrors showing exactly on which accounts and how a constraint was violated
    - inside-handler user code will use an `error!` macro that takes a string and an error code and creates an AnchorError that also includes the line number and file name
- if dispatch returns an error
    - anchor logs the error information once in human readable form
    - and once in base64 encoded form
    - converts the anchorerror back into a programerror and returns it

**Comment by paul-schaaf** [comment]
I would also suggest merging #789 and #823 for one issue that fully designs and implements proper error reporting, I think that will be easier to develop and better designed

**Comment by paul-schaaf** [comment]
open question: how do we make error msgs dynamic?

e.g. error `#msg[..]` could be defined with `"{}"` syntax like `format!`. the new error creation macro then takes args that fill the `{}`

**Comment by paul-schaaf** [comment]
another feature that could be added as part of this milestone: more `require` statements
e.g. `require_mut(account)`, `require_signer(account)`, `require_owner(account, owner)` etc.

This is useful for instructions that use `remaining_accounts`

**Comment by paul-schaaf** [comment]
We should talk more about specification of this issue

The following code
```
pub fn initialize(ctx: Context<Initialize>) -> AnchorResult<()> {
        error!(MyError::SomeError)
}
```

results in the following logs
```
Program log: AnchorError thrown in programs/compute/src/lib.rs:9 in program: Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS. Error Code: SomeError. Error Number: 6000. Error Message: Some error has been thrown.
```

which is the type of error (AnchorError vs ProgramError). The file and line. The ErrorCode/ErrorName, the error number, and the error message.

This information seems pretty good to me.  Im going to adjust the error msgs to make them dynamic so then youd have even more freedom. I added the program id so errors are useful even if CPIs are happening

the question is, what's the best way to log this? I think we should definitely provide an option to just log it like this. It's very useful for developing and would also be useful info in the explorer. But maybe there should be an option to turn this off.
but imo we also need something more machine friendly. We could do what events do and encode and then log the encoded error as well.



Also, the error msg above costs ~ 14K compute units which is pretty expensive. However, about 12K of those come from turning the public key into a string. This is not necessary because we can hardcode the string somewhere.

**Comment by armaniferrante** [comment]
Note that logging the program id is redundant, because it can be easily inferred when looking at the log context (every CPI shows the program being invoked).

The machine readable / structured error would be useful (and preferred) for funneling error messages to the client, rather than what we do now which is parse error codes. Defining a error type that is logge din the same way we do events sounds good.

E.g.

```
#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct ErrorEvent {
  line: u64,
  msg: String,
  code: u32,
  ...
}
```

One question is do we want to add a unique header to such an error event like we do for regular events. I think so, so that we can parse it from the logs easily. Something simple like `sha256("internal:error")[..4]` as the discriminator with the new header. Might be good to do this as a separate change, since it will also require client plumbing. 

Related https://github.com/project-serum/anchor/issues/126#issuecomment-815466853.
