### ISSUE TITLE
Anchor test not working on M1 mac

### ISSUE THREAD

**Issue by JIVIN0902** [project-serum/anchor#876]
I am trying to run anchor on my m1 mac. But the anchor test command is failing on my project.
My solana cli is 1.8.0 and still this issue is persisting.

I have a local solana-test validator on with this.

If I switch off the local validator It gives a socket hangup error.

      Is initialized!:
     Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:4964:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Connection.sendRawTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:4923:20)
      at async sendAndConfirmRawTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:6907:21)
      at async Provider.send (node_modules/@project-serum/anchor/dist/cjs/provider.js:85:22)
      at async Object.rpc [as initialize] (node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
      at async Context.<anonymous> (tests/mysolanaapp.js:12:14)

**Comment by bluuesz** [comment]
+1 Same issue with M1

**Comment by bluuesz** [comment]
This helped me, I ended up reading the log in `.anchor/test-ledger/test-ledger-log.txt` and what was causing the error is that the `anchor test` was running my broken binary from arm64 and not my x86_64

https://github.com/project-serum/anchor/issues/825#issuecomment-937740776

**Comment by spacemandev-git** [comment]
Posting the workaround to this by dimfeld:

For anyone with the error FetchError: request to http://localhost:8899/ failed, the problem you're having is that on M1 w/o Rosetta the Solana validator doesn't support a certain feature used to compile the Solana bytecode, but it also doesn't know it needs to turn it off.  Here's the workaround:
1. Run the validator manually using solana-test-validator --no-bpf-jit and leave it running whenever you're running a test. You can also use the --reset option to have it automatically clear out the existing test-ledger directory to save some disk space.
2. To run tests, use anchor test --skip-local-validator. This will tell Anchor to run the test against the validator you started instead of running it's own.

There's a Github issue open on Anchor to allow running anchor test in such a way that it will run the validator with --no-bpf-jit but that's not implemented yet, so for now this should work.

**Comment by JIVIN0902** [comment]
@spacemandev-git I followed these steps and I got this error:

Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist

Any Idea why that is happening?

**Comment by fanatid** [comment]
@JIVIN0902 you need to start test validator with `--bpf-program` option.

On M1 test-validator should be launched with `--no-bpf-jit` flag. Once https://github.com/solana-labs/solana/pull/21215 will be merged `anchor test` should work.

**Comment by ishaanh** [comment]
Hi @spacemandev-git 
I have a Macbook M1 and anchor test is not working for me 

When I run anchor test, I receive the following error:
<img width="825" alt="Screen Shot 2021-12-27 at 2 59 38 PM" src="https://user-images.githubusercontent.com/51675727/147503455-007619e2-42b5-43c9-9693-f4d160b78093.png">

I tried changing my local validator (solana-test-validator --no-bpf-jit) and skipping the local validator (anchor test --skip-local-validator) but receive the same error every time

I'd love any insight on how to fix this

**Comment by JIVIN0902** [comment]
@ishaanh I struggled with this a lot too. I recommend building solana and rust using rosetta. 
``` softwareupdate install rosetta```
and download homebrew through arch x86_64
https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/
Highly recommend u read this article and build all solana related stuff rosetta. 
Hope it helps.

**Comment by dev-tom-0108** [comment]
I had the same issue but I changed the network rpc.
Then it woks well.
